--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: main_answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_answer (
    id bigint NOT NULL,
    text text NOT NULL,
    is_correct boolean NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.main_answer OWNER TO postgres;

--
-- Name: main_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_appointment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_appointment (
    id bigint NOT NULL,
    user_name character varying(150) NOT NULL,
    user_phone character varying(25) NOT NULL,
    user_comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    group_id bigint,
    user_id bigint,
    status character varying(10) NOT NULL,
    subject_id bigint
);


ALTER TABLE public.main_appointment OWNER TO postgres;

--
-- Name: main_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_question (
    id bigint NOT NULL,
    text text NOT NULL,
    test_id bigint NOT NULL,
    image character varying(100) NOT NULL
);


ALTER TABLE public.main_question OWNER TO postgres;

--
-- Name: main_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_schedule (
    id bigint NOT NULL,
    day_of_week integer NOT NULL,
    start_time time without time zone NOT NULL,
    teacher_id bigint NOT NULL,
    student_group_id bigint NOT NULL,
    duration interval NOT NULL
);


ALTER TABLE public.main_schedule OWNER TO postgres;

--
-- Name: main_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_studentgroup; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_studentgroup (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    teacher_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    unregistered_users_count integer NOT NULL
);


ALTER TABLE public.main_studentgroup OWNER TO postgres;

--
-- Name: main_studentgroup_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_studentgroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_studentgroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_studentgroup_students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_studentgroup_students (
    id bigint NOT NULL,
    studentgroup_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.main_studentgroup_students OWNER TO postgres;

--
-- Name: main_studentgroup_students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_studentgroup_students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_studentgroup_students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_subject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_subject (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.main_subject OWNER TO postgres;

--
-- Name: main_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_teacher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_teacher (
    user_id bigint NOT NULL,
    bio text NOT NULL
);


ALTER TABLE public.main_teacher OWNER TO postgres;

--
-- Name: main_teacher_subjects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_teacher_subjects (
    id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    subject_id bigint NOT NULL
);


ALTER TABLE public.main_teacher_subjects OWNER TO postgres;

--
-- Name: main_teacher_subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_teacher_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_teacher_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_test; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_test (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    subject_id bigint NOT NULL
);


ALTER TABLE public.main_test OWNER TO postgres;

--
-- Name: main_test_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_testresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_testresult (
    id bigint NOT NULL,
    score integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    test_id bigint NOT NULL,
    user_id bigint,
    user_answers jsonb
);


ALTER TABLE public.main_testresult OWNER TO postgres;

--
-- Name: main_testresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_testresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_testresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role integer NOT NULL,
    avatar character varying(100) NOT NULL,
    phone_number character varying(25) NOT NULL
);


ALTER TABLE public.main_user OWNER TO postgres;

--
-- Name: main_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.main_user_groups OWNER TO postgres;

--
-- Name: main_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.main_user_user_permissions OWNER TO postgres;

--
-- Name: main_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Пользователь	6	add_user
22	Can change Пользователь	6	change_user
23	Can delete Пользователь	6	delete_user
24	Can view Пользователь	6	view_user
25	Can add Предмет	7	add_subject
26	Can change Предмет	7	change_subject
27	Can delete Предмет	7	delete_subject
28	Can view Предмет	7	view_subject
29	Can add Преподаватель	8	add_teacher
30	Can change Преподаватель	8	change_teacher
31	Can delete Преподаватель	8	delete_teacher
32	Can view Преподаватель	8	view_teacher
33	Can add Группа студентов	9	add_studentgroup
34	Can change Группа студентов	9	change_studentgroup
35	Can delete Группа студентов	9	delete_studentgroup
36	Can view Группа студентов	9	view_studentgroup
37	Can add Расписание	10	add_schedule
38	Can change Расписание	10	change_schedule
39	Can delete Расписание	10	delete_schedule
40	Can view Расписание	10	view_schedule
41	Can add Запись	11	add_appointment
42	Can change Запись	11	change_appointment
43	Can delete Запись	11	delete_appointment
44	Can view Запись	11	view_appointment
45	Can add Заявка	12	add_application
46	Can change Заявка	12	change_application
47	Can delete Заявка	12	delete_application
48	Can view Заявка	12	view_application
49	Can add Тест	13	add_test
50	Can change Тест	13	change_test
51	Can delete Тест	13	delete_test
52	Can view Тест	13	view_test
53	Can add Вопрос	14	add_question
54	Can change Вопрос	14	change_question
55	Can delete Вопрос	14	delete_question
56	Can view Вопрос	14	view_question
57	Can add Результат теста	15	add_testresult
58	Can change Результат теста	15	change_testresult
59	Can delete Результат теста	15	delete_testresult
60	Can view Результат теста	15	view_testresult
61	Can add Ответ	16	add_answer
62	Can change Ответ	16	change_answer
63	Can delete Ответ	16	delete_answer
64	Can view Ответ	16	view_answer
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2024-07-03 01:37:00.083253+03	1	Математика	1	[{"added": {}}]	7	1
2	2024-07-03 01:37:13.166221+03	2	Русский язык	1	[{"added": {}}]	7	1
3	2024-07-03 01:37:20.241018+03	3	Информатика	1	[{"added": {}}]	7	1
4	2024-07-03 01:37:27.523206+03	4	Обществознание	1	[{"added": {}}]	7	1
5	2024-07-03 01:37:36.540601+03	5	Биология	1	[{"added": {}}]	7	1
6	2024-07-03 01:37:43.154775+03	6	Химия	1	[{"added": {}}]	7	1
7	2024-07-03 01:37:52.911546+03	7	Физика	1	[{"added": {}}]	7	1
8	2024-07-03 01:38:00.332231+03	8	Литература	1	[{"added": {}}]	7	1
9	2024-07-03 01:39:19.38587+03	11	Изот Горшков (andre84) (Преподаватель)	3		6	1
10	2024-07-03 01:39:19.386872+03	6	Фаина Лебедев (dementikuznetsov) (Преподаватель)	3		6	1
11	2024-07-03 01:39:19.387872+03	16	Валентина Жданова (dobroslavbelov) (Преподаватель)	3		6	1
12	2024-07-03 01:39:19.387872+03	2	Всеслав Овчинников (gorshkovpotap) (Преподаватель)	3		6	1
13	2024-07-03 01:39:19.388873+03	7	Сильвестр Евдокимов (grigorevvitali) (Преподаватель)	3		6	1
14	2024-07-03 01:39:19.388873+03	5	Гордей Гуляев (gurevasvetlana) (Преподаватель)	3		6	1
15	2024-07-03 01:39:19.388873+03	18	Моисей Колесников (itihonov) (Преподаватель)	3		6	1
16	2024-07-03 01:39:19.389873+03	3	Игнатий Павлов (jevseeva) (Преподаватель)	3		6	1
17	2024-07-03 01:39:19.389873+03	4	Харлампий Белякова (krjukovamarfa) (Преподаватель)	3		6	1
18	2024-07-03 01:39:19.390873+03	9	Савелий Гущин (longin1992) (Преподаватель)	3		6	1
19	2024-07-03 01:39:19.390873+03	14	Эраст Шарапова (maksimiljanorehov) (Преподаватель)	3		6	1
20	2024-07-03 01:39:19.390873+03	17	Евдокия Пестова (rjurik_2016) (Преподаватель)	3		6	1
21	2024-07-03 01:39:19.391873+03	10	Эммануил Белов (semenovvjacheslav) (Преподаватель)	3		6	1
22	2024-07-03 01:39:19.391873+03	15	Гордей Авдеева (veronika2018) (Преподаватель)	3		6	1
23	2024-07-03 01:39:19.391873+03	12	Вениамин Комарова (vissarion_1990) (Преподаватель)	3		6	1
24	2024-07-03 01:39:19.392873+03	13	Агап Зимина (vladlen1995) (Преподаватель)	3		6	1
25	2024-07-03 01:39:19.392873+03	8	Милий Доронина (vsemil2009) (Преподаватель)	3		6	1
26	2024-07-03 01:39:28.798958+03	20	Владимир Кабанова (abramovmaksim) (Преподаватель)	3		6	1
27	2024-07-03 01:39:28.800105+03	23	Георгий Пестов (demjanermakov) (Преподаватель)	3		6	1
28	2024-07-03 01:39:28.800105+03	22	Игорь Самойлова (kallistrat2019) (Преподаватель)	3		6	1
29	2024-07-03 01:39:28.801108+03	21	Никон Копылова (ljubosmisl_2016) (Преподаватель)	3		6	1
30	2024-07-03 01:39:28.801108+03	19	Любим Константинов (oartemev) (Преподаватель)	3		6	1
31	2024-07-03 01:39:28.802108+03	24	Лазарь Волкова (simon41) (Преподаватель)	3		6	1
32	2024-07-03 01:41:27.060775+03	30	Хава Губашева (hava) (Преподаватель)	2	[{"changed": {"fields": ["Username", "First name", "Last name", "Email address", "\\u0410\\u0432\\u0430\\u0442\\u0430\\u0440\\u043a\\u0430"]}}]	6	1
33	2024-07-03 01:46:05.517464+03	38	Яха Исламова (yakhita) (Преподаватель)	2	[{"changed": {"fields": ["Username", "First name", "Last name", "Email address"]}}]	6	1
34	2024-07-03 01:46:15.828157+03	38	Яха Исламова (yakhita) (Преподаватель)	2	[{"changed": {"fields": ["\\u0410\\u0432\\u0430\\u0442\\u0430\\u0440\\u043a\\u0430"]}}]	6	1
35	2024-07-03 01:46:44.303896+03	38	Яха Исламова (yakhita)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u0435\\u0434\\u043c\\u0435\\u0442\\u044b", "\\u041d\\u0430\\u0432\\u044b\\u043a\\u0438"]}}]	8	1
36	2024-07-03 01:46:59.521965+03	30	Хава Губашева (hava)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u0435\\u0434\\u043c\\u0435\\u0442\\u044b", "\\u041d\\u0430\\u0432\\u044b\\u043a\\u0438"]}}]	8	1
37	2024-07-03 01:47:37.810207+03	28	Пров Копылова (fkolobov) (Преподаватель)	3		6	1
38	2024-07-03 01:47:49.473395+03	35	Флорентин Евдокимов (irina_77) (Преподаватель)	3		6	1
39	2024-07-03 02:03:46.889653+03	1	 (admin) (Менеджер)	2	[{"changed": {"fields": ["\\u0420\\u043e\\u043b\\u044c"]}}]	6	1
40	2024-07-03 02:05:09.539317+03	38	Яха Исламова (yakhita)	2	[{"changed": {"name": "\\u0413\\u0440\\u0443\\u043f\\u043f\\u0430 \\u0441\\u0442\\u0443\\u0434\\u0435\\u043d\\u0442\\u043e\\u0432", "object": "\\u042f\\u0445\\u0430 \\u0418\\u0441\\u043b\\u0430\\u043c\\u043e\\u0432\\u0430 (yakhita) - \\u0413\\u0440\\u0443\\u043f\\u043f\\u0430 1", "fields": ["\\u041f\\u0440\\u0435\\u0434\\u043c\\u0435\\u0442"]}}]	8	1
41	2024-07-03 02:06:01.196403+03	38	Яха Исламова (yakhita)	2	[{"changed": {"name": "\\u0420\\u0430\\u0441\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435", "object": "yakhita - \\u0413\\u0440\\u0443\\u043f\\u043f\\u0430 1 - \\u0412\\u0442\\u043e\\u0440\\u043d\\u0438\\u043a", "fields": ["\\u0414\\u0435\\u043d\\u044c \\u043d\\u0435\\u0434\\u0435\\u043b\\u0438", "\\u0412\\u0440\\u0435\\u043c\\u044f \\u043d\\u0430\\u0447\\u0430\\u043b\\u0430"]}}, {"changed": {"name": "\\u0420\\u0430\\u0441\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435", "object": "yakhita - \\u0413\\u0440\\u0443\\u043f\\u043f\\u0430 1 - \\u0421\\u0443\\u0431\\u0431\\u043e\\u0442\\u0430", "fields": ["\\u0414\\u0435\\u043d\\u044c \\u043d\\u0435\\u0434\\u0435\\u043b\\u0438", "\\u0412\\u0440\\u0435\\u043c\\u044f \\u043d\\u0430\\u0447\\u0430\\u043b\\u0430"]}}, {"deleted": {"name": "\\u0420\\u0430\\u0441\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435", "object": "yakhita - \\u0413\\u0440\\u0443\\u043f\\u043f\\u0430 2 - \\u041f\\u044f\\u0442\\u043d\\u0438\\u0446\\u0430"}}]	8	1
42	2024-07-04 13:15:30.400173+03	1	Запись esta в Группа 1	2	[{"changed": {"fields": ["\\u0421\\u0442\\u0430\\u0442\\u0443\\u0441"]}}]	11	1
43	2024-07-21 01:23:32.225603+03	1	Вариант 1	1	[{"added": {}}]	13	1
44	2024-07-21 01:23:55.000943+03	1	Вопрос 1: Схема строения атома химического элемента кремния...	1	[{"added": {}}]	14	1
45	2024-07-21 01:24:05.574871+03	2	Вопрос 2: Положительную степень окисления хлор проявляет в с...	1	[{"added": {}}]	14	1
46	2024-07-21 01:24:21.253986+03	3	Вопрос 3: Кислотные свойства высших оксидов химических элеме...	1	[{"added": {}}]	14	1
47	2024-07-21 01:24:42.459874+03	1	Ответ 1: 2, 8, 18,  4...	1	[{"added": {}}]	16	1
48	2024-07-21 01:24:57.384496+03	2	Ответ 2: 2, 8, 8, 2...	1	[{"added": {}}]	16	1
49	2024-07-21 01:25:08.979346+03	3	Ответ 3: 2, 8, 6...	1	[{"added": {}}]	16	1
50	2024-07-21 01:25:15.844104+03	4	Ответ 4: 2, 8, 8...	1	[{"added": {}}]	16	1
51	2024-07-21 01:25:28.995311+03	5	Ответ 5: NaCl...	1	[{"added": {}}]	16	1
52	2024-07-21 01:25:42.185265+03	6	Ответ 6: PCl5...	1	[{"added": {}}]	16	1
53	2024-07-21 01:25:48.58383+03	7	Ответ 7: HCl...	1	[{"added": {}}]	16	1
54	2024-07-21 01:25:55.043531+03	8	Ответ 8: Cl2O7...	1	[{"added": {}}]	16	1
55	2024-07-21 01:26:11.685819+03	9	Ответ 9: усиливаются...	1	[{"added": {}}]	16	1
56	2024-07-21 01:26:26.460067+03	10	Ответ 10: ослабевают...	1	[{"added": {}}]	16	1
57	2024-07-21 01:29:34.690944+03	4	Ответ 4: 2, 8, 8...	2	[]	16	1
58	2024-07-21 01:29:42.72398+03	3	Ответ 3: 2, 8, 6...	2	[]	16	1
59	2024-07-21 01:29:51.730488+03	2	Ответ 2: 2, 8, 8, 2...	2	[]	16	1
60	2024-07-21 01:30:00.818664+03	1	Ответ 1: 2, 8, 18,  4...	2	[]	16	1
61	2024-07-21 01:30:24.507575+03	3	Вопрос 3: Кислотные свойства высших оксидов химических элеме...	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u0432\\u043e\\u043f\\u0440\\u043e\\u0441\\u0430"]}}]	14	1
62	2024-07-21 01:31:01.127069+03	1	Вопрос 1: Схема строения атома химического элемента кремния...	2	[]	14	1
63	2024-07-21 21:43:54.728845+03	1	Вариант 1 - 5 баллов	3		15	1
64	2024-07-21 22:04:28.256064+03	3	Вариант 1 - 5 баллов	3		15	1
65	2024-07-21 22:04:28.257063+03	2	Вариант 1 - 5 баллов	3		15	1
66	2024-07-25 15:06:44.827631+03	1	 (admin) (Менеджер)	2	[]	6	1
99	2024-07-25 21:24:44.385538+03	1	Вопрос 1: Схема строения атома химического элемента кремния...	2	[]	14	1
100	2024-07-25 21:24:49.634967+03	4	Вопрос 4: В каком варианте ответа выделенное слово употребле...	1	[{"added": {}}]	14	1
101	2024-07-25 21:25:09.197615+03	11	Ответ 11: Воспитатель ещё раз напомнил родителям, чтобы они,...	1	[{"added": {}}]	16	1
102	2024-07-25 21:25:15.840119+03	12	Ответ 12: Конкретный эффект от увеличения угла обзора при ра...	1	[{"added": {}}]	16	1
103	2024-07-29 14:34:32.281353+03	1	Тест по химии	2	[{"changed": {"fields": ["\\u041f\\u0440\\u0435\\u0434\\u043c\\u0435\\u0442"]}}]	13	1
104	2024-08-01 16:59:24.027243+03	33	Вопрос 33: Определите, какое значение будет в ячейке С3:...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
105	2024-08-01 16:59:40.962576+03	30	Вопрос 30: На рисунке в ЭТ выделен некоторый диапазон. Укажит...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
106	2024-08-01 16:59:58.46676+03	2	Тест по информатике	2	[{"changed": {"fields": ["\\u041f\\u0440\\u0435\\u0434\\u043c\\u0435\\u0442"]}}]	13	1
107	2024-08-08 16:19:38.607037+03	8	Ответ 8: Cl2O7<sub>2</sub>...	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u043e\\u0442\\u0432\\u0435\\u0442\\u0430"]}}]	16	1
108	2024-08-08 16:23:51.329622+03	8	Ответ 8: Cl<sub>2</sub>O<sub>7</sub>...	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u043e\\u0442\\u0432\\u0435\\u0442\\u0430"]}}]	16	1
109	2024-08-09 23:25:25.49861+03	37	Зосима Ильин [ermakovavera] (Преподаватель)	3		6	1
110	2024-08-09 23:25:25.501129+03	39	Ростислав Мясников [erofe00] (Преподаватель)	3		6	1
111	2024-08-09 23:25:25.502456+03	30	Хава Губашева [hava] (Преподаватель)	3		6	1
112	2024-08-09 23:25:25.503457+03	31	Фадей Козлов [ija85] (Преподаватель)	3		6	1
113	2024-08-09 23:25:25.503457+03	26	Евгений Николаева [ipatikapustin] (Преподаватель)	3		6	1
114	2024-08-09 23:25:25.504457+03	43	Ксения Вишняков [julian2001] (Преподаватель)	3		6	1
115	2024-08-09 23:25:25.504457+03	34	Марк Костин [kovalevvladilen] (Преподаватель)	3		6	1
116	2024-08-09 23:25:25.504457+03	32	Аполлон Цветков [lukinazinaida] (Преподаватель)	3		6	1
117	2024-08-09 23:25:25.505457+03	41	Чеслав Уварова [lukjan27] (Преподаватель)	3		6	1
118	2024-08-09 23:25:25.505457+03	29	Элеонора Назаров [markovmilen] (Преподаватель)	3		6	1
119	2024-08-09 23:25:25.505457+03	36	Порфирий Егоров [platon80] (Преподаватель)	3		6	1
120	2024-08-09 23:25:25.506457+03	44	Вышеслав Денисова [platongorbachev] (Преподаватель)	3		6	1
121	2024-08-09 23:25:25.507458+03	27	Лазарь Максимова [serafim_18] (Преподаватель)	3		6	1
122	2024-08-09 23:25:25.507458+03	25	Аполлинарий Воронцова [sharapovanatoli] (Преподаватель)	3		6	1
123	2024-08-09 23:25:25.508458+03	33	Автоном Красильников [tit_53] (Преподаватель)	3		6	1
124	2024-08-09 23:25:25.508458+03	40	Мокей Шестаков [ustin_2007] (Преподаватель)	3		6	1
125	2024-08-09 23:25:25.508458+03	38	Яха Исламова [yakhita] (Преподаватель)	3		6	1
126	2024-08-09 23:25:25.509962+03	42	Пимен Захарова [zkonstantinov] (Преподаватель)	3		6	1
127	2024-08-09 23:25:25.509962+03	49	Алисултанов Хасан [алисултанов.хасан] (Преподаватель)	3		6	1
128	2024-08-09 23:25:25.510976+03	54	Байсаева Элана [байсаева.элана] (Преподаватель)	3		6	1
129	2024-08-09 23:25:25.510976+03	53	Исаев Мовсар [исаев.мовсар] (Преподаватель)	3		6	1
130	2024-08-09 23:25:25.510976+03	47	Кагирова Хадижат [кагирова.хадижат] (Преподаватель)	3		6	1
131	2024-08-09 23:25:25.512279+03	46	Муртазалиев Ризван [муртазалиев.ризван] (Преподаватель)	3		6	1
132	2024-08-09 23:25:25.512279+03	51	Мусаев Хамзат [мусаев.хамзат] (Преподаватель)	3		6	1
133	2024-08-09 23:25:25.512279+03	45	Мусаитов Магомед [мусаитов.магомед] (Преподаватель)	3		6	1
134	2024-08-09 23:25:25.513279+03	52	Пасаева Лидия [пасаева.лидия] (Преподаватель)	3		6	1
135	2024-08-09 23:25:25.513279+03	48	Хайдарханова Зара [хайдарханова.зара] (Преподаватель)	3		6	1
136	2024-08-09 23:25:25.514279+03	50	Эльдерханов Хаважи [эльдерханов.хаважи] (Преподаватель)	3		6	1
137	2024-08-09 23:30:32.023144+03	59	Алисултанов Хасан [алисултанов.хасан] (Преподаватель)	3		6	1
138	2024-08-09 23:30:32.025144+03	64	Байсаева Элана [байсаева.элана] (Преподаватель)	3		6	1
139	2024-08-09 23:30:32.025144+03	63	Исаев Мовсар [исаев.мовсар] (Преподаватель)	3		6	1
140	2024-08-09 23:30:32.026144+03	57	Кагирова Хадижат [кагирова.хадижат] (Преподаватель)	3		6	1
141	2024-08-09 23:30:32.026144+03	56	Муртазалиев Ризван [муртазалиев.ризван] (Преподаватель)	3		6	1
142	2024-08-09 23:30:32.027144+03	61	Мусаев Хамзат [мусаев.хамзат] (Преподаватель)	3		6	1
143	2024-08-09 23:30:32.027144+03	55	Мусаитов Магомед [мусаитов.магомед] (Преподаватель)	3		6	1
144	2024-08-09 23:30:32.028145+03	62	Пасаева Лидия [пасаева.лидия] (Преподаватель)	3		6	1
145	2024-08-09 23:30:32.028145+03	58	Хайдарханова Зара [хайдарханова.зара] (Преподаватель)	3		6	1
146	2024-08-09 23:30:32.028145+03	60	Эльдерханов Хаважи [эльдерханов.хаважи] (Преподаватель)	3		6	1
147	2024-08-09 23:43:25.938+03	74	Байсаева Элана	2	[{"changed": {"fields": ["\\u0411\\u0438\\u043e\\u0433\\u0440\\u0430\\u0444\\u0438\\u044f"]}}]	8	1
148	2024-08-10 02:43:27.120576+03	3	Тест по профильной математике	3		13	1
149	2024-08-10 02:44:35.220785+03	3	Запись Магомед в без группы	3		11	1
150	2024-08-10 03:13:00.692098+03	44	Вопрос 44: Найдите корень уравнения...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
151	2024-08-10 03:13:08.43714+03	45	Вопрос 45: Решите уравнение...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
152	2024-08-10 03:13:15.043097+03	46	Вопрос 46: Найдите корень уравнения...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
153	2024-08-10 03:13:21.443255+03	47	Вопрос 47: Найдите корень уравнения:...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
154	2024-08-10 03:13:28.306643+03	48	Вопрос 48: Найдите значение выражения...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
155	2024-08-10 03:13:34.065215+03	49	Вопрос 49: Найдите значение выражения при...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
156	2024-08-10 03:13:44.516118+03	50	Вопрос 50: Найдите значение выражения:...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
157	2024-08-10 03:14:08.332009+03	51	Вопрос 51: Найдите значение выражения...	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u0432\\u043e\\u043f\\u0440\\u043e\\u0441\\u0430", "\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
158	2024-08-10 03:14:13.781261+03	52	Вопрос 52: Найдите значение выражения...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
159	2024-08-10 03:14:35.062454+03	41	Вопрос 41: В треугольнике ABC отрезок DE — средняя линия. Пло...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
160	2024-08-10 03:15:22.056441+03	41	Вопрос 41: В треугольнике ABC отрезок DE — средняя линия. Пло...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
161	2024-08-10 03:15:27.828986+03	42	Вопрос 42: Два угла треугольника равны 58° и 72°. Найдите туп...	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0440\\u0442\\u0438\\u043d\\u043a\\u0430"]}}]	14	1
162	2024-08-10 03:23:20.593574+03	191	Ответ 191: -0.125...	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u043e\\u0442\\u0432\\u0435\\u0442\\u0430", "\\u041f\\u0440\\u0430\\u0432\\u0438\\u043b\\u044c\\u043d\\u044b\\u0439 \\u043e\\u0442\\u0432\\u0435\\u0442"]}}]	16	1
163	2024-08-10 03:23:54.396156+03	191	Ответ 191: -1.25...	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u043e\\u0442\\u0432\\u0435\\u0442\\u0430"]}}]	16	1
164	2024-08-10 03:24:49.445604+03	194	Ответ 194: -125...	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u043e\\u0442\\u0432\\u0435\\u0442\\u0430"]}}]	16	1
165	2025-04-08 21:01:23.448224+03	73	Исаев Мовсар	2	[{"changed": {"fields": ["\\u0411\\u0438\\u043e\\u0433\\u0440\\u0430\\u0444\\u0438\\u044f"]}}]	8	1
166	2025-04-08 21:02:10.510135+03	67	Кагирова Хадижат	2	[{"changed": {"fields": ["\\u0411\\u0438\\u043e\\u0433\\u0440\\u0430\\u0444\\u0438\\u044f"]}}]	8	1
167	2025-04-10 17:47:01.836798+03	69	Алисултанов Хасан [алисултанов.хасан] (Преподаватель)	3		6	1
168	2025-04-10 17:47:01.841382+03	74	Байсаева Элана [байсаева.элана] (Преподаватель)	3		6	1
169	2025-04-10 17:47:01.841382+03	73	Исаев Мовсар [исаев.мовсар] (Преподаватель)	3		6	1
170	2025-04-10 17:47:01.842395+03	67	Кагирова Хадижат [кагирова.хадижат] (Преподаватель)	3		6	1
171	2025-04-10 17:47:01.843426+03	66	Муртазалиев Ризван [муртазалиев.ризван] (Преподаватель)	3		6	1
172	2025-04-10 17:47:01.843426+03	71	Мусаев Хамзат [мусаев.хамзат] (Преподаватель)	3		6	1
173	2025-04-10 17:47:01.844435+03	65	Мусаитов Магомед [мусаитов.магомед] (Преподаватель)	3		6	1
174	2025-04-10 17:47:01.844435+03	72	Пасаева Лидия [пасаева.лидия] (Преподаватель)	3		6	1
175	2025-04-10 17:47:01.845441+03	68	Хайдарханова Зара [хайдарханова.зара] (Преподаватель)	3		6	1
176	2025-04-10 17:47:01.845441+03	70	Эльдерханов Хаважи [эльдерханов.хаважи] (Преподаватель)	3		6	1
177	2025-04-10 18:06:53.583269+03	83	Тазуркаев Амир	2	[]	8	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	main	user
7	main	subject
8	main	teacher
9	main	studentgroup
10	main	schedule
11	main	appointment
12	main	application
13	main	test
14	main	question
15	main	testresult
16	main	answer
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-07-03 00:03:10.620084+03
2	contenttypes	0002_remove_content_type_name	2024-07-03 00:03:10.623084+03
3	auth	0001_initial	2024-07-03 00:03:10.661023+03
4	auth	0002_alter_permission_name_max_length	2024-07-03 00:03:10.664024+03
5	auth	0003_alter_user_email_max_length	2024-07-03 00:03:10.667024+03
6	auth	0004_alter_user_username_opts	2024-07-03 00:03:10.66954+03
7	auth	0005_alter_user_last_login_null	2024-07-03 00:03:10.671541+03
8	auth	0006_require_contenttypes_0002	2024-07-03 00:03:10.672542+03
9	auth	0007_alter_validators_add_error_messages	2024-07-03 00:03:10.674959+03
10	auth	0008_alter_user_username_max_length	2024-07-03 00:03:10.67696+03
11	auth	0009_alter_user_last_name_max_length	2024-07-03 00:03:10.680482+03
12	auth	0010_alter_group_name_max_length	2024-07-03 00:03:10.684483+03
13	auth	0011_update_proxy_permissions	2024-07-03 00:03:10.688484+03
14	auth	0012_alter_user_first_name_max_length	2024-07-03 00:03:10.690708+03
15	main	0001_initial	2024-07-03 00:03:10.728726+03
16	admin	0001_initial	2024-07-03 00:03:10.74672+03
17	admin	0002_logentry_remove_auto_add	2024-07-03 00:03:10.750634+03
18	admin	0003_logentry_add_action_flag_choices	2024-07-03 00:03:10.754635+03
19	main	0002_subject_alter_user_avatar_alter_user_phone_number_and_more	2024-07-03 00:03:10.792954+03
20	main	0003_studentgroup_alter_user_avatar_schedule_and_more	2024-07-03 00:03:10.836788+03
21	main	0004_alter_schedule_options_alter_studentgroup_options_and_more	2024-07-03 00:03:10.858743+03
22	main	0005_remove_teacher_subjects_teachersubject	2024-07-03 00:03:10.883456+03
23	main	0006_studentgroup_price_teacher_subjects_and_more	2024-07-03 00:03:10.909485+03
24	main	0007_teacher_skills	2024-07-03 00:03:10.915758+03
25	main	0008_alter_teacher_skills	2024-07-03 00:03:10.927169+03
26	main	0009_remove_teacher_groups_studentgroup_teacher	2024-07-03 00:03:10.943231+03
27	main	0010_remove_schedule_subject_studentgroup_subject	2024-07-03 00:03:10.962605+03
28	main	0011_alter_teacher_skills_alter_teacher_user_appointment	2024-07-03 00:03:10.990768+03
29	main	0012_alter_appointment_user_and_more	2024-07-03 00:03:11.006777+03
30	main	0013_alter_studentgroup_price	2024-07-03 00:03:11.018299+03
31	main	0014_alter_appointment_user_alter_appointment_user_phone_and_more	2024-07-03 00:03:11.034313+03
32	main	0015_studentgroup_students	2024-07-03 00:03:11.053125+03
33	main	0016_appointment_status	2024-07-03 00:03:11.06075+03
34	main	0017_remove_schedule_end_time_schedule_duration	2024-07-03 00:03:11.070257+03
35	main	0018_remove_studentgroup_price	2024-07-03 00:03:11.076774+03
36	main	0019_application	2024-07-03 00:03:11.093126+03
37	main	0020_alter_application_user_phone	2024-07-03 00:03:11.099643+03
38	sessions	0001_initial	2024-07-03 00:03:11.111033+03
39	main	0021_studentgroup_created_at	2024-07-03 01:59:38.334522+03
40	main	0022_question_answer_test_question_test_testresult	2024-07-20 23:47:23.212441+03
41	main	0023_testresult_user_answers	2024-07-21 20:42:09.067842+03
42	main	0024_alter_testresult_user	2024-07-21 20:54:50.36434+03
43	main	0025_remove_application_updated_at_application_status	2024-07-25 17:36:57.929838+03
44	main	0026_studentgroup_unregistered_users_count	2024-07-25 18:51:30.425175+03
45	main	0027_appointment_subject_alter_appointment_group_and_more	2024-07-26 01:43:40.307822+03
46	main	0028_alter_appointment_status	2024-07-29 02:00:19.936896+03
47	main	0029_question_image	2024-07-30 17:33:58.250868+03
48	main	0030_remove_teacher_skills	2024-08-13 15:00:43.084984+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
c4raxyrf7v7mwadxghyecq18narxec1j	.eJxVjDsOwjAQBe_iGllZO-sklPScIdpfcAA5Uj4V4u4QKQW0b2bey_W0rbnfFpv7Ud3ZgTv9bkzysLIDvVO5TV6mss4j-13xB138dVJ7Xg737yDTkr91w4Y1C1UgEZugXUiAlZrGhjFhJIRAUYcobVsH60BbGxgCpMSSENz7A90DN5I:1sU41Y:nMJR3fz0X1cS2HuURp_vadwAj8MOGpmNxCDGjb06DvI	2024-07-31 15:44:48.9917+03
98c8a7y6j5w9ys6nukvnrchzbnsuivsi	.eJxVjMsOwiAQAP-FsyHyLPXo3W8gC7srVQNJaU_GfzckPeh1ZjJvEWHfStw7rXFBcRHeidMvTJCfVIfBB9R7k7nVbV2SHIk8bJe3hvS6Hu3foEAv46vxjEzBm1mrlBRztuCJJz05VITZmGSDNcyGNaBxxN6FjA5CysrO4vMFK1w5BA:1sdqBG:0-WTuAnvwKl7uTflAZcv0x7fUrRkE7udoetyvXdBM4I	2024-08-27 14:59:14.634219+03
a7sx0izbbqeyckbz5la3l1s6xrahg5s1	.eJxVjDsOwjAQBe_iGllZO-sklPScIdpfcAA5Uj4V4u4QKQW0b2bey_W0rbnfFpv7Ud3ZgTv9bkzysLIDvVO5TV6mss4j-13xB138dVJ7Xg737yDTkr91w4Y1C1UgEZugXUiAlZrGhjFhJIRAUYcobVsH60BbGxgCpMSSENz7A90DN5I:1sdqKs:tBzN4iYuhxWXe4lhpzjThcOsWtCzaL8Pwme1SxgnYeY	2024-08-27 15:09:10.419333+03
vdxgbustujclnb4t3lsasi8bqhvhuk5g	.eJxVjDsOwjAQBe_iGllZO-sklPScIdpfcAA5Uj4V4u4QKQW0b2bey_W0rbnfFpv7Ud3ZgTv9bkzysLIDvVO5TV6mss4j-13xB138dVJ7Xg737yDTkr91w4Y1C1UgEZugXUiAlZrGhjFhJIRAUYcobVsH60BbGxgCpMSSENz7A90DN5I:1sZWdn:tGDie-MJFrYkF_A_b0-ZpSCaDrV3PObOWmon2eRAXPI	2024-08-15 17:18:51.692569+03
9t2fpoig2tenlzu5wr85c3pm1mfm5vdk	.eJxVjDsOwjAQBe_iGllZO-sklPScIdpfcAA5Uj4V4u4QKQW0b2bey_W0rbnfFpv7Ud3ZgTv9bkzysLIDvVO5TV6mss4j-13xB138dVJ7Xg737yDTkr91w4Y1C1UgEZugXUiAlZrGhjFhJIRAUYcobVsH60BbGxgCpMSSENz7A90DN5I:1scbde:qDoIKAH21cgvP_87cjuxXvW1BmAzpwtmo7LKxm8iFEE	2024-08-24 05:15:26.597957+03
gg8nav31ap3efco2mfm3yncqh7odrtvj	.eJxVjMEOwiAQRP-FsyErW6B49N5vILC7StXQpLQn47_bJj3ocea9mbeKaV1KXJvMcWR1UQjq9FvmRE-pO-FHqvdJ01SXecx6V_RBmx4mltf1cP8OSmplW5O11pFNBo1IpltwZ-c7EBPABuPE45ZzD5g7FvIJrCBkZgQyBntSny_zrzeW:1sOmWo:IkaXEYWiJDH9wW-vQpaJdUK3EahjkVWM9SxpoOpySs8	2024-07-17 02:03:14.391331+03
wspxevrld3dqfb6bndn2f0nr3pob6w70	.eJxVjDsOwjAQBe_iGllZO-sklPScIdpfcAA5Uj4V4u4QKQW0b2bey_W0rbnfFpv7Ud3ZgTv9bkzysLIDvVO5TV6mss4j-13xB138dVJ7Xg737yDTkr91w4Y1C1UgEZugXUiAlZrGhjFhJIRAUYcobVsH60BbGxgCpMSSENz7A90DN5I:1sc39m:l9_M2zKgEJq3wV2U8uBYL0ywez8UdnqScUHP0BRDIeA	2024-08-22 16:26:18.674581+03
tmwz5k7lt6500mnjcota7zn6dysp3zml	.eJxVjDsOwjAQBe_iGllZO-sklPScIdpfcAA5Uj4V4u4QKQW0b2bey_W0rbnfFpv7Ud3ZgTv9bkzysLIDvVO5TV6mss4j-13xB138dVJ7Xg737yDTkr91w4Y1C1UgEZugXUiAlZrGhjFhJIRAUYcobVsH60BbGxgCpMSSENz7A90DN5I:1u2tUT:Eaw_DsgF_pWe8CB78rArVMJNACPWLuS2q14yyNzjq5w	2025-04-24 18:06:53.75632+03
yox3xgt635aypc22o8x7l5niji9v17gm	.eJxVjDsOwjAQBe_iGllZO-sklPScIdpfcAA5Uj4V4u4QKQW0b2bey_W0rbnfFpv7Ud3ZgTv9bkzysLIDvVO5TV6mss4j-13xB138dVJ7Xg737yDTkr91w4Y1C1UgEZugXUiAlZrGhjFhJIRAUYcobVsH60BbGxgCpMSSENz7A90DN5I:1sPJVZ:t99XZkaD_K-wJAGoRhCGkON5b7kBZ5EcMt4ud5AJ108	2024-07-18 13:16:09.595609+03
vlzm12kzqyk28a4d1udr13kbv69a4vl6	.eJxVjEEOwiAQRe_C2pAy7Qjj0n3PQAYGpGpKUtqV8e7apAvd_vfefynP21r81tLiJ1EXZQd1-h0Dx0eadyJ3nm9VxzqvyxT0ruiDNj1WSc_r4f4dFG7lWyMwMIdsCcj0JqCLwkSDSAcoCNnKQJ1xkDEbOQNkkETQkzAYh6jeHweUN60:1u2DZv:jJPpEY_dft7LJhq3zoXWkqjts-OCKUVWe4W9BcV174U	2025-04-22 21:21:43.147184+03
\.


--
-- Data for Name: main_answer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_answer (id, text, is_correct, question_id) FROM stdin;
91	эквивалентность	f	23
92	импликацию	t	23
93	дизъюнкцию	f	23
94	инверсией	t	24
1	2818 4	f	1
2	2882	f	1
3	286	f	1
4	28 4	t	1
5	NaCl	f	2
6	PCl5	f	2
7	HCl	f	2
8	Cl<sub>2</sub>O<sub>7</sub>	t	2
9	усиливаются	f	3
10	ослабевают	t	3
11	остаются неизменными	f	3
12	сначала усиливаются, затем ослабевают	f	3
13	сульфатами	f	4
14	сульфитами	f	4
15	сульфидами	t	4
16	сернистыми металлами	f	4
17	магний	t	5
18	кальций	f	5
19	стронций	f	5
20	барий	f	5
21	АlРО4	f	6
22	АgСl	f	6
23	NaОН	t	6
24	ВаSО4	f	6
25	АlРО4	f	7
26	АgСl2	t	7
27	NaОН	f	7
28	ВаSО4	f	7
29	Zn + HCl = H2 + ZnCl2	f	8
30	Cl2 + Fe = FeCl3	f	8
31	P + O2 = P2O5	f	8
32	Na2S + HCl = H2S + NaCl	t	8
33	медь гидроксид меди (2)	f	9
34	натрий гидроксида натрия	f	9
35	вода гидроксид калия	f	9
36	серная кислота оксид серы	t	9
37	Ca и Na2O	t	10
38	Na2O и Cu	f	10
39	CuO и N2O5	f	10
40	ZnO и SO2	f	10
41	природа реагирующих веществ	f	11
42	температура	f	11
43	концентрация реагирующих веществ	f	11
44	тип химической реакции	t	11
45	NaBr + AgNO3 = NaNO3 + AgBr	f	12
46	(NH4)2CO3 = 2NH3 + CO2 + H2O	t	12
47	NH4OH + HNO3 = NH4NO3 + H2O	f	12
48	2NH4OH + CuCl2 = 2NH4Cl + Cu(OH)2	f	12
49	СnH2n	f	13
50	СnH2n+2	t	13
51	СnH2n-2	f	13
52	СnH2n-6	f	13
53	гомологами	f	14
54	изомерами	t	14
55	полимерами	f	14
56	пептидами	f	14
57	алканов	f	15
58	алкинов	t	15
59	аренов	f	15
60	алкенов	f	15
61	Дегидратации	t	16
62	Дегалогенирования	f	16
63	Дегидрогалогенирования	f	16
64	Дегидрирования	f	16
65	спирты	f	17
66	альдегиды	f	17
67	карбоновые кислоты	t	17
68	арены	f	17
69	спирт	t	18
70	кислота	f	18
71	альдегид	f	18
72	алкан	f	18
73	for	f	19
74	i	f	19
75	print	t	19
76	input	f	19
77	int(input())	t	20
78	print()	f	20
79	while	f	20
80	for	f	20
81	print(f)	t	21
82	n = int(input())	f	21
83	t = input()	f	21
84	print(2+4)	f	21
85	456	f	22
86	674	f	22
87	324	t	22
88	78	f	22
89	инверсию	f	23
90	конъюнкцию	f	23
95	эквивалентностью	f	24
96	дизъюнкцией	f	24
97	конъюнкцией	f	24
98	импликацией	f	24
99	инверсией	f	25
100	эквивалентностью	f	25
101	конъюнкцией	f	25
102	дизъюнкцией	t	25
103	импликацией	f	25
104	инверсию	f	26
105	дизъюнкцию	f	26
106	импликацию	f	26
107	конъюнкцию	t	26
108	эквивалентность	f	26
109	110110000	t	27
110	1010010101	f	27
111	10000101	f	27
112	111010101	f	27
113	многофункциональный инструмент для подготовки и оформления текстовых документов	t	28
114	выполнение расчетов, построение диаграмм, анализ данных, автоматизация трудоемких задач и прочие операции с электронными таблицами	f	28
115	подготовка красочных и интерактивных презентаций, как для семейных праздников, так и для бизнес-выступлений	f	28
116	разработка и управление персональными базами данных	f	28
117	многофункциональный инструмент для подготовки и оформления текстовых документов	f	29
118	выполнение расчетов, построение диаграмм, анализ данных, автоматизация трудоемких задач и прочие операции с электронными таблицами	t	29
119	подготовка красочных и интерактивных презентаций, как для семейных праздников, так и для бизнес-выступлений	f	29
120	разработка и управление персональными базами данных	f	29
121	А6:С3	f	30
122	А3 - С6	f	30
123	А3:С6	t	30
124	А6 - А3	f	30
125	^	f	31
126	=	t	31
127	%	f	31
128	!	f	31
129	128	t	32
130	256	f	32
131	512	f	32
132	1024	f	32
133	12	f	33
134	13	f	33
135	25	t	33
136	1	f	33
164	12	f	41
165	48	f	41
166	24	f	41
167	96	t	41
168	130	t	42
169	58	f	42
170	150	f	42
171	50	f	42
172	0.375	t	43
173	0.037	f	43
174	0.75	f	43
175	0.37	f	43
176	27	f	44
177	-27	t	44
178	-1	f	44
179	1	f	44
180	10	f	45
181	0	f	45
182	-1	t	45
183	1	f	45
184	-3	f	46
185	5	f	46
186	3	f	46
187	-5	t	46
188	-125	f	47
189	0.125	f	47
190	-0.25	f	47
192	-25	t	48
193	0.25	f	48
195	25	f	48
196	1331	f	49
197	121	t	49
198	1	f	49
199	11	f	49
200	500	f	50
201	-425	f	50
202	425	t	50
203	450	f	50
204	1	f	51
205	0.81	f	51
206	3	f	51
207	9	t	51
208	-0.5	f	52
209	-4	f	52
210	4	t	52
211	0.5	f	52
191	-1.25	t	47
194	-125	f	48
\.


--
-- Data for Name: main_appointment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_appointment (id, user_name, user_phone, user_comment, created_at, group_id, user_id, status, subject_id) FROM stdin;
5	Магомед	+7 900 777 05 05		2024-08-13 15:09:03.920284+03	\N	\N	CREATED	2
\.


--
-- Data for Name: main_question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_question (id, text, test_id, image) FROM stdin;
1	Схема строения атома химического элемента кремния	1	
2	Положительную степень окисления хлор проявляет в соединении	1	
3	Кислотные свойства высших оксидов химических элементов VА-группы периодической таблицы Д. И. Менделеева в ряду N2O5→P2O5→As2O5→Sb2O5	1	
4	Соединения серы с металлами называют	1	
5	Металл, не относящийся к щёлочноземельным	1	
6	Какой из указанных формул обозначена формула основания?	1	
7	В какой из указанных формул допущена ошибка при написании формулы?	1	
8	Среди приведенных схем химических реакций к реакциям обмена относится:	1	
9	С гидроксидом натрия реагируют каждое из пары веществ:	1	
10	Вода взаимодействует с каждым из веществ, формулы которых	1	
11	Фактор, не влияющий на скорость химических реакций	1	
12	Реакцией ионного обмена не является реакция	1	
13	Общая формула алканов:	1	
14	Вещества, имеющие формулы СН3 – О – СН3 и СН3 – СН2 – ОН, являются	1	
15	Ацетилен принадлежит к гомологическому ряду:	1	
16	Реакции, в ходе которых от молекулы вещества отщепляется вода, называют реакциями:	1	
17	Функциональную группу –CООH содержат:	1	
18	Продуктом гидратации этилена является:	1	
19	Какая команда отвечает за вывод информации на экран?	2	
20	Какая команда отвечает за ввод числа с клавиатуры	2	
21	Какой код написаный ниже выдаст ошибку?	2	
22	Что будет выведено на экран?\na = 6 ** 2\nprint(a * 9)	2	
23	Какую операцию на формальном языке алгебры высказываний принято обозначать значком «→»?	2	
24	Присоединение частицы «не» к высказыванию называется ...	2	
25	Объединение двух (или нескольких) высказываний с помощью союза «или» называется ...	2	
26	Какую операцию на формальном языке алгебры высказываний принято обозначать значком «&» либо «˄»?	2	
27	Переведите число 432 из десятичной в двоичную систему счисления.	2	
28	Что такое MS Word?	2	
29	Что такое MS Excel?	2	
31	Выберите знак, с которого должна начинаться любая формула в ЭТ.	2	
32	Оцените информационный объем слова “каникулы”, считая, что каждый символ закодирован двумя байтами. Ответ представьте в битах.	2	
33	Определите, какое значение будет в ячейке С3:	2	info_2.jpg
30	На рисунке в ЭТ выделен некоторый диапазон. Укажите верную запись этого диапазона в ЭТ.	2	info_1.jpg
43	Перед началом футбольного матча судья бросает монетку, чтобы определить, какая из команд начнёт игру с мячом. Команда «Труд» играет три матча с разными командами. Найдите вероятность того, что в этих играх «Труд» выиграет жребий ровно один раз.	4	
44	Найдите корень уравнения	4	prof_4.png
45	Решите уравнение	4	prof_5.png
46	Найдите корень уравнения	4	prof_6.png
47	Найдите корень уравнения:	4	prof_7.png
48	Найдите значение выражения	4	prof_8.png
49	Найдите значение выражения при	4	prof_9.png
50	Найдите значение выражения:	4	prof_10.png
51	Найдите значение выражения	4	prof_11.png
52	Найдите значение выражения	4	prof_12.png
42	Два угла треугольника равны 58° и 72°. Найдите тупой угол, который образуют высоты треугольника, выходящие из вершин этих углов. Ответ дайте в градусах.	4	prof_alg_test_DCllOO3.png
41	В треугольнике ABC отрезок DE — средняя линия. Площадь треугольника CDE равна 24. Найдите площадь треугольника ABC.	4	
\.


--
-- Data for Name: main_schedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_schedule (id, day_of_week, start_time, teacher_id, student_group_id, duration) FROM stdin;
\.


--
-- Data for Name: main_studentgroup; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_studentgroup (id, name, teacher_id, subject_id, created_at, unregistered_users_count) FROM stdin;
\.


--
-- Data for Name: main_studentgroup_students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_studentgroup_students (id, studentgroup_id, user_id) FROM stdin;
\.


--
-- Data for Name: main_subject; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_subject (id, name) FROM stdin;
1	Математика
2	Русский язык
3	Информатика
4	Обществознание
5	Биология
6	Химия
7	Физика
8	Литература
9	Русский язык и литература.
10	Математика (базовая/профиль)
11	Профильная математика
12	Чеченский язык и литература
13	Базовая математика
14	ИКТ
15	Чеченский язык
\.


--
-- Data for Name: main_teacher; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_teacher (user_id, bio) FROM stdin;
82	Стаж - 9 лет. Готовит к ЕГЭ более 6 лет. Финалист проекта «Лидеры в образовании». Средний результат: 70/80 баллов. Лучший результат - 92 балла.
76	Общий стаж работы: 13 лет. Готовит к ЕГЭ более 8 лет. Самый высокий результат ученика 96 баллов, лучший результат в Чеченской Республике! Награждён грамотой Российской Федерации за 'Большой личный вклад в практическую подготовку учащихся и воспитанников!' Победитель конкурса педагогических работников Чеченской Республики. В 2024 году сам сдал экзамен ЕГЭ по профильной математике на 100 баллов.
77	Была активисткой и одной из лучших студентов ЧГПУ, участвовала во многих педагогических форумах и проектах. Окончила ЧГПУ на красный диплом по профилям «Математика» и «Информатика». 4-ый год занимается репетиторством по профильной математике ЕГЭ. Выпустила 150+ учеников. Подготовила большое количество учеников с нуля. Лучший результат - 84 балла
78	Почётный работник воспитания и просвещения Российской Федерации! Выпустил 2-х 100-балльников.
79	Готовит к ЕГЭ более 6 лет. Средний результат подготовки учащихся - +80 баллов
75	Общий стаж работы 8 лет, подготовку к ЕГЭ по обществознанию ведет более 3 лет. Полуфиналист всероссийского конкурса «Флагманы образования. Россия- страна возможностей». Подготовила победителя ВСОШ по г.Грозный. Ежегодно получает грамоты за подготовку детей к ОГЭ и ЕГЭ. Средний балл - 70+. Лучший результат- 77 баллов
80	Готовит выпускников к ОГЭ/ЕГЭ с 2018г. Победитель конкурса молодежных проектов Северо-Кавказского федерального округа среди физических лиц в 2023 году. Руководитель научно-практического трека «Химия». Победитель VIII Всероссийского студенческого конкурса исследовательских проектов. Наставник победителя и финалиста всероссийских конкурсов. Средний результат подготовки учащихся: 80+ баллов
81	Стаж работы в сфере образования 4 года. Подготовка детей к ЕГЭ по биологии. Результаты в среднем 70 баллов. Подготовила призера муниципального этапа Всероссийской Олимпиады школьников. Почетная грамота от Департамента образования.
84	Общий стаж: 39 лет. Пед.стаж: 12 лет. Участник разработок рабочих тетрадей по чеченскому языку. Активный участник проекта «UROK95.RU». Награжден Почетной грамотой Министерства Просвещения РФ.
83	Стаж-7 лет. Готовлю к ОГЭ и ЕГЭ 6 лет. Лауреат городского этапа Всероссийского Конкурса «Учитель года России»-2024. Средний результат: 70/80 баллов. Лучший результат: 95 баллов
\.


--
-- Data for Name: main_teacher_subjects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_teacher_subjects (id, teacher_id, subject_id) FROM stdin;
155	75	4
156	76	11
157	77	13
158	77	11
159	78	3
160	78	14
161	79	13
162	79	3
163	80	6
164	81	5
165	82	2
166	82	8
167	83	2
168	83	8
169	84	15
170	84	8
\.


--
-- Data for Name: main_test; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_test (id, name, created_at, updated_at, subject_id) FROM stdin;
1	Тест по химии	2024-07-29 03:00:00+03	2024-07-29 14:34:32.280353+03	6
2	Тест по информатике	2024-07-29 03:00:00+03	2024-08-01 16:59:58.46575+03	3
4	Тест по профильной математике	2024-08-10 02:43:34.533764+03	2024-08-10 02:43:34.533764+03	11
\.


--
-- Data for Name: main_testresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_testresult (id, score, created_at, test_id, user_id, user_answers) FROM stdin;
4	5	2024-07-21 22:04:53.364158+03	1	\N	{"1": 4, "2": 7, "3": 9}
5	5	2024-07-21 22:05:49.959474+03	1	\N	{"1": 1, "2": 8, "3": 10}
6	0	2024-07-21 22:45:49.728679+03	1	\N	{"1": 1, "2": 7, "3": 9}
7	0	2024-07-21 22:46:44.351954+03	1	\N	{"1": 3, "2": 6, "3": 10}
8	0	2024-07-21 22:48:36.01076+03	1	\N	{"1": 3, "2": 8, "3": 9}
9	2	2024-07-21 22:49:39.325461+03	1	\N	{"1": 3, "2": 8, "3": 9}
10	0	2024-07-24 14:44:57.60313+03	1	\N	{"1": 1, "2": 7, "3": 9}
11	0	2024-07-24 15:56:18.52801+03	1	\N	{"1": 1, "2": 7, "3": 9}
12	1	2024-07-24 15:56:31.615184+03	1	\N	{"1": 1, "2": 7, "3": 10}
13	1	2024-07-24 15:56:59.734857+03	1	\N	{"1": 3, "2": 7, "3": 9}
14	1	2024-07-24 15:58:51.492609+03	1	\N	{"1": 3, "2": 7, "3": 9}
15	1	2024-07-24 16:09:34.918477+03	1	\N	{"1": 3, "2": 7, "3": 9}
16	0	2024-07-24 16:12:06.115625+03	1	\N	{"1": 1, "2": 5, "3": 9}
17	0	2024-07-24 16:13:53.5449+03	1	\N	{"1": 1, "2": 5, "3": 9}
18	0	2024-07-24 16:17:51.078836+03	1	\N	{"1": 1, "2": 5, "3": 9}
19	1	2024-07-24 16:18:04.685992+03	1	\N	{"1": 3, "2": 7, "3": 9}
20	0	2024-07-24 16:18:42.693512+03	1	\N	{"1": 1, "2": 7, "3": 9}
21	0	2024-07-25 15:05:14.917081+03	1	\N	{"1": 2, "2": 7, "3": 9}
54	1	2024-07-25 21:25:36.000491+03	1	\N	{"1": 1, "2": 7, "3": 9, "4": 11}
55	1	2024-07-25 21:27:44.52308+03	1	\N	{"1": 1, "2": 5, "3": 9, "4": 11}
56	3	2024-07-29 13:28:35.870794+03	1	\N	{"1": 3, "2": 7, "3": 11, "4": 15, "5": 19, "6": 23, "7": 27, "8": 31, "9": 33, "10": 39, "11": 43, "12": 48, "13": 52, "14": 55, "15": 59, "16": 63, "17": 67, "18": 71}
57	2	2024-07-29 14:32:10.664342+03	1	\N	{"1": 3, "2": 7, "3": 10, "4": 16, "5": 19, "6": 24, "7": 27, "8": 32, "9": 35, "10": 40, "11": 43, "12": 48, "13": 52, "14": 55, "15": 60, "16": 63, "17": 68, "18": 71}
58	11	2024-08-01 17:01:44.084699+03	2	\N	{"19": 75, "20": 77, "21": 81, "22": 87, "23": 92, "24": 94, "25": 102, "26": 107, "27": 109, "28": 113, "29": 117, "30": 121, "31": 125, "32": 131, "33": 135}
59	10	2024-08-10 03:26:06.818049+03	4	\N	{"41": 165, "42": 168, "43": 172, "44": 176, "45": 182, "46": 187, "47": 191, "48": 192, "49": 197, "50": 202, "51": 207, "52": 210}
\.


--
-- Data for Name: main_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, avatar, phone_number) FROM stdin;
84	pbkdf2_sha256$720000$OjlTGTBd4OJzGaii4KvvhK$S9+KKDxdZTHOnRuwYXcZbAOwWszwuvR4X53wCHWw8WQ=	\N	f	мусаев.хамзат	Мусаев	Хамзат		f	t	2025-04-10 17:51:50.03356+03	2		
1	pbkdf2_sha256$720000$GUw5JSrbE1WKW3XRyD6x8L$vr7YTi4cgh2u1mWkKCRxU6Hr664uWCQhfRrTgn7a7cw=	2025-04-08 21:07:15.860673+03	t	admin				t	t	2024-07-03 01:33:43+03	3		
75	pbkdf2_sha256$720000$6tSVJFqNtI9YiBmjYCp1kg$CVJv+2EntTZ6vDN8B/5R62qz9vRocJwUiM/GQHIs6b8=	\N	f	узаева.халима	Узаева	Халима		f	t	2025-04-10 17:51:46.108749+03	2		
76	pbkdf2_sha256$720000$fAjixxSFrocBmw7m40Tibm$g2B9Z20Z/yx7lA8vcMgWDM4/3vocPnXnIexhx20r9RM=	\N	f	эльдерханов.хаважи	Эльдерханов	Хаважи		f	t	2025-04-10 17:51:46.568446+03	2		
77	pbkdf2_sha256$720000$62y0Wk8tDtS4JO0kCfkKjp$hWxPfLFAdulU3M3yyV+wRF+A9ajD7PgbwCsDjzWfUGA=	\N	f	пасаева.лидия	Пасаева	Лидия		f	t	2025-04-10 17:51:47.006512+03	2		
78	pbkdf2_sha256$720000$NaMlZIbksixnGWdJO7BVTF$N3LGIyp92glqZL08Ip39kvfKW+V5M7VyBUc2dxiraN4=	\N	f	мусаитов.магомед	Мусаитов	Магомед		f	t	2025-04-10 17:51:47.439286+03	2		
79	pbkdf2_sha256$720000$LEUq96tIGiiH3LjWXnrccc$X1ZP/x3m94YbH+2F1b6HVggBahm5aMwIxztOAcBlClY=	\N	f	кагирова.хадижат	Кагирова	Хадижат		f	t	2025-04-10 17:51:47.872399+03	2		
80	pbkdf2_sha256$720000$eg8Ipqe4wX5SgLUGvHU9mU$O7zP8ROIJFIcPB/Jyzu5lmb6SzI88UNhE8/jWEncZqo=	\N	f	исаев.мовсар	Исаев	Мовсар		f	t	2025-04-10 17:51:48.31282+03	2		
81	pbkdf2_sha256$720000$1NGgo6tgwfcnyIEI1ON7Rm$WzWeeBoOdpBfVpfyqcaUt9kRcfdDzu7QSSQ6X371N+g=	\N	f	байсаева.элана	Байсаева	Элана		f	t	2025-04-10 17:51:48.742572+03	2		
82	pbkdf2_sha256$720000$nxk93e7or3pCgTdu1FjCyR$VkQExelb5QQ8xFgqB6UROkcyyL3BRyjrz5scUAimuX8=	\N	f	хайдарханова.зара	Хайдарханова	Зара		f	t	2025-04-10 17:51:49.179975+03	2		
83	pbkdf2_sha256$720000$mKdA4BPQ9eL9GJWIx3FjAT$c5t3EKVNcwy9nua6jsBIlpOJIbAX2nZTuz0B4H8xyrA=	\N	f	тазуркаев.амир	Тазуркаев	Амир		f	t	2025-04-10 17:51:49.597012+03	2		
\.


--
-- Data for Name: main_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: main_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 177, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 48, true);


--
-- Name: main_answer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_answer_id_seq', 211, true);


--
-- Name: main_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_appointment_id_seq', 5, true);


--
-- Name: main_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_question_id_seq', 52, true);


--
-- Name: main_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_schedule_id_seq', 202, true);


--
-- Name: main_studentgroup_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_studentgroup_id_seq', 126, true);


--
-- Name: main_studentgroup_students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_studentgroup_students_id_seq', 48, true);


--
-- Name: main_subject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_subject_id_seq', 15, true);


--
-- Name: main_teacher_subjects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_teacher_subjects_id_seq', 170, true);


--
-- Name: main_test_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_test_id_seq', 4, true);


--
-- Name: main_testresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_testresult_id_seq', 59, true);


--
-- Name: main_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_user_groups_id_seq', 1, false);


--
-- Name: main_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_user_id_seq', 84, true);


--
-- Name: main_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: main_answer main_answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_answer
    ADD CONSTRAINT main_answer_pkey PRIMARY KEY (id);


--
-- Name: main_appointment main_appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_appointment
    ADD CONSTRAINT main_appointment_pkey PRIMARY KEY (id);


--
-- Name: main_question main_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_question
    ADD CONSTRAINT main_question_pkey PRIMARY KEY (id);


--
-- Name: main_schedule main_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_schedule
    ADD CONSTRAINT main_schedule_pkey PRIMARY KEY (id);


--
-- Name: main_studentgroup main_studentgroup_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_studentgroup
    ADD CONSTRAINT main_studentgroup_pkey PRIMARY KEY (id);


--
-- Name: main_studentgroup_students main_studentgroup_studen_studentgroup_id_user_id_07d79fe2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_studentgroup_students
    ADD CONSTRAINT main_studentgroup_studen_studentgroup_id_user_id_07d79fe2_uniq UNIQUE (studentgroup_id, user_id);


--
-- Name: main_studentgroup_students main_studentgroup_students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_studentgroup_students
    ADD CONSTRAINT main_studentgroup_students_pkey PRIMARY KEY (id);


--
-- Name: main_subject main_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_subject
    ADD CONSTRAINT main_subject_pkey PRIMARY KEY (id);


--
-- Name: main_teacher main_teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_teacher
    ADD CONSTRAINT main_teacher_pkey PRIMARY KEY (user_id);


--
-- Name: main_teacher_subjects main_teacher_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_teacher_subjects
    ADD CONSTRAINT main_teacher_subjects_pkey PRIMARY KEY (id);


--
-- Name: main_teacher_subjects main_teacher_subjects_teacher_id_subject_id_1b99805d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_teacher_subjects
    ADD CONSTRAINT main_teacher_subjects_teacher_id_subject_id_1b99805d_uniq UNIQUE (teacher_id, subject_id);


--
-- Name: main_test main_test_name_subject_id_60bf9f01_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_test
    ADD CONSTRAINT main_test_name_subject_id_60bf9f01_uniq UNIQUE (name, subject_id);


--
-- Name: main_test main_test_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_test
    ADD CONSTRAINT main_test_pkey PRIMARY KEY (id);


--
-- Name: main_testresult main_testresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_testresult
    ADD CONSTRAINT main_testresult_pkey PRIMARY KEY (id);


--
-- Name: main_user_groups main_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_pkey PRIMARY KEY (id);


--
-- Name: main_user_groups main_user_groups_user_id_group_id_ae195797_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_user_id_group_id_ae195797_uniq UNIQUE (user_id, group_id);


--
-- Name: main_user main_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user
    ADD CONSTRAINT main_user_pkey PRIMARY KEY (id);


--
-- Name: main_user_user_permissions main_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: main_user_user_permissions main_user_user_permissions_user_id_permission_id_96b9fadf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_user_id_permission_id_96b9fadf_uniq UNIQUE (user_id, permission_id);


--
-- Name: main_user main_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user
    ADD CONSTRAINT main_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: main_answer_question_id_96405437; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_answer_question_id_96405437 ON public.main_answer USING btree (question_id);


--
-- Name: main_appointment_group_id_4909c05f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_appointment_group_id_4909c05f ON public.main_appointment USING btree (group_id);


--
-- Name: main_appointment_subject_id_d9963ea3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_appointment_subject_id_d9963ea3 ON public.main_appointment USING btree (subject_id);


--
-- Name: main_appointment_user_id_05ac45c5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_appointment_user_id_05ac45c5 ON public.main_appointment USING btree (user_id);


--
-- Name: main_question_test_id_3ff0a13c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_question_test_id_3ff0a13c ON public.main_question USING btree (test_id);


--
-- Name: main_schedule_student_group_id_f4cd51b5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_schedule_student_group_id_f4cd51b5 ON public.main_schedule USING btree (student_group_id);


--
-- Name: main_schedule_teacher_id_6e24501c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_schedule_teacher_id_6e24501c ON public.main_schedule USING btree (teacher_id);


--
-- Name: main_studentgroup_students_studentgroup_id_7ed3f701; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_studentgroup_students_studentgroup_id_7ed3f701 ON public.main_studentgroup_students USING btree (studentgroup_id);


--
-- Name: main_studentgroup_students_user_id_0c775b12; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_studentgroup_students_user_id_0c775b12 ON public.main_studentgroup_students USING btree (user_id);


--
-- Name: main_studentgroup_subject_id_6ad406d6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_studentgroup_subject_id_6ad406d6 ON public.main_studentgroup USING btree (subject_id);


--
-- Name: main_studentgroup_teacher_id_064ba65b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_studentgroup_teacher_id_064ba65b ON public.main_studentgroup USING btree (teacher_id);


--
-- Name: main_teacher_subjects_subject_id_890d64d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_teacher_subjects_subject_id_890d64d7 ON public.main_teacher_subjects USING btree (subject_id);


--
-- Name: main_teacher_subjects_teacher_id_9425bd4e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_teacher_subjects_teacher_id_9425bd4e ON public.main_teacher_subjects USING btree (teacher_id);


--
-- Name: main_test_subject_id_b10b4fb5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_test_subject_id_b10b4fb5 ON public.main_test USING btree (subject_id);


--
-- Name: main_testresult_test_id_5c3f135c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_testresult_test_id_5c3f135c ON public.main_testresult USING btree (test_id);


--
-- Name: main_testresult_user_id_85c41775; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_testresult_user_id_85c41775 ON public.main_testresult USING btree (user_id);


--
-- Name: main_user_groups_group_id_a337ba62; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_user_groups_group_id_a337ba62 ON public.main_user_groups USING btree (group_id);


--
-- Name: main_user_groups_user_id_df502602; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_user_groups_user_id_df502602 ON public.main_user_groups USING btree (user_id);


--
-- Name: main_user_user_permissions_permission_id_cd2b56a3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_user_user_permissions_permission_id_cd2b56a3 ON public.main_user_user_permissions USING btree (permission_id);


--
-- Name: main_user_user_permissions_user_id_451ce57f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_user_user_permissions_user_id_451ce57f ON public.main_user_user_permissions USING btree (user_id);


--
-- Name: main_user_username_6330637b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_user_username_6330637b_like ON public.main_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_answer main_answer_question_id_96405437_fk_main_question_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_answer
    ADD CONSTRAINT main_answer_question_id_96405437_fk_main_question_id FOREIGN KEY (question_id) REFERENCES public.main_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_appointment main_appointment_group_id_4909c05f_fk_main_studentgroup_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_appointment
    ADD CONSTRAINT main_appointment_group_id_4909c05f_fk_main_studentgroup_id FOREIGN KEY (group_id) REFERENCES public.main_studentgroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_appointment main_appointment_subject_id_d9963ea3_fk_main_subject_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_appointment
    ADD CONSTRAINT main_appointment_subject_id_d9963ea3_fk_main_subject_id FOREIGN KEY (subject_id) REFERENCES public.main_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_appointment main_appointment_user_id_05ac45c5_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_appointment
    ADD CONSTRAINT main_appointment_user_id_05ac45c5_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_question main_question_test_id_3ff0a13c_fk_main_test_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_question
    ADD CONSTRAINT main_question_test_id_3ff0a13c_fk_main_test_id FOREIGN KEY (test_id) REFERENCES public.main_test(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_schedule main_schedule_student_group_id_f4cd51b5_fk_main_studentgroup_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_schedule
    ADD CONSTRAINT main_schedule_student_group_id_f4cd51b5_fk_main_studentgroup_id FOREIGN KEY (student_group_id) REFERENCES public.main_studentgroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_schedule main_schedule_teacher_id_6e24501c_fk_main_teacher_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_schedule
    ADD CONSTRAINT main_schedule_teacher_id_6e24501c_fk_main_teacher_user_id FOREIGN KEY (teacher_id) REFERENCES public.main_teacher(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_studentgroup_students main_studentgroup_st_studentgroup_id_7ed3f701_fk_main_stud; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_studentgroup_students
    ADD CONSTRAINT main_studentgroup_st_studentgroup_id_7ed3f701_fk_main_stud FOREIGN KEY (studentgroup_id) REFERENCES public.main_studentgroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_studentgroup_students main_studentgroup_students_user_id_0c775b12_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_studentgroup_students
    ADD CONSTRAINT main_studentgroup_students_user_id_0c775b12_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_studentgroup main_studentgroup_subject_id_6ad406d6_fk_main_subject_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_studentgroup
    ADD CONSTRAINT main_studentgroup_subject_id_6ad406d6_fk_main_subject_id FOREIGN KEY (subject_id) REFERENCES public.main_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_studentgroup main_studentgroup_teacher_id_064ba65b_fk_main_teacher_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_studentgroup
    ADD CONSTRAINT main_studentgroup_teacher_id_064ba65b_fk_main_teacher_user_id FOREIGN KEY (teacher_id) REFERENCES public.main_teacher(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_teacher_subjects main_teacher_subject_teacher_id_9425bd4e_fk_main_teac; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_teacher_subjects
    ADD CONSTRAINT main_teacher_subject_teacher_id_9425bd4e_fk_main_teac FOREIGN KEY (teacher_id) REFERENCES public.main_teacher(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_teacher_subjects main_teacher_subjects_subject_id_890d64d7_fk_main_subject_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_teacher_subjects
    ADD CONSTRAINT main_teacher_subjects_subject_id_890d64d7_fk_main_subject_id FOREIGN KEY (subject_id) REFERENCES public.main_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_teacher main_teacher_user_id_d3a9b5ac_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_teacher
    ADD CONSTRAINT main_teacher_user_id_d3a9b5ac_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_test main_test_subject_id_b10b4fb5_fk_main_subject_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_test
    ADD CONSTRAINT main_test_subject_id_b10b4fb5_fk_main_subject_id FOREIGN KEY (subject_id) REFERENCES public.main_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_testresult main_testresult_test_id_5c3f135c_fk_main_test_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_testresult
    ADD CONSTRAINT main_testresult_test_id_5c3f135c_fk_main_test_id FOREIGN KEY (test_id) REFERENCES public.main_test(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_testresult main_testresult_user_id_85c41775_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_testresult
    ADD CONSTRAINT main_testresult_user_id_85c41775_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_groups main_user_groups_group_id_a337ba62_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_group_id_a337ba62_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_groups main_user_groups_user_id_df502602_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_user_id_df502602_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_user_permissions main_user_user_permi_permission_id_cd2b56a3_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permi_permission_id_cd2b56a3_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_user_permissions main_user_user_permissions_user_id_451ce57f_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_user_id_451ce57f_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

