# Generated by Django 5.0.6 on 2024-06-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_schedule_options_alter_studentgroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='main.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='main.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Предмет преподавателя',
                'verbose_name_plural': 'Предметы преподавателя',
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
