# Generated by Django 5.0.6 on 2024-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_studentgroup_price_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.JSONField(default=list, verbose_name='Навыки'),
        ),
    ]
