# Generated by Django 5.0.6 on 2024-06-13 01:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_schedule_subject_studentgroup_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('user_phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Допустимо до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('user_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.studentgroup', verbose_name='Группа')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
