# Generated by Django 5.0.6 on 2024-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studentgroup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создано'), ('ACCEPTED', 'Принято'), ('REJECTED', 'Отклонено')], default='CREATED', max_length=10, verbose_name='Статус'),
        ),
    ]
