# Generated by Django 5.0.6 on 2024-06-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_schedule_end_time_schedule_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='price',
        ),
    ]
