# Generated by Django 5.0.6 on 2024-06-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_phone',
            field=models.CharField(max_length=25, verbose_name='Номер телефона'),
        ),
    ]
