# Generated by Django 5.0.6 on 2024-07-02 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_application_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
