# Generated by Django 5.0.6 on 2024-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_application_updated_at_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='unregistered_users_count',
            field=models.IntegerField(default=0),
        ),
    ]
