# Generated by Django 5.0.6 on 2024-07-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_studentgroup_unregistered_users_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.studentgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создано'), ('ACCEPTED', 'Принято'), ('REJECTED', 'Отменено')], default='CREATED', max_length=10, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
