# Generated by Django 5.0.6 on 2024-07-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_appointment_subject_alter_appointment_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создано'), ('ACCEPTED', 'Принято'), ('REJECTED', 'Отменено'), ('PROCESSED', 'Обработан')], default='CREATED', max_length=10, verbose_name='Статус'),
        ),
    ]
