# Generated by Django 5.0.6 on 2024-08-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='skills',
        ),
    ]
